spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quartz?serverTimezone=UTC&useSSL=false
    password: 123456
    username: root
  quartz:
    job-store-type: memory
    jdbc:
      initialize-schema: always


covid:
  daily:
    data:
      api: https://api.covidtracking.com/v1/states/current.json
cron:
  expression: 0 15 10 15 * ?
fixedDelay:
  in:
    milliseconds: 1000
fixedRate:
  in:
    milliseconds: 1000
retry:
  maxAttempts: 2
  maxDelay: 100

