server:
  port: 6001
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order?useSSL=false
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: create
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        auto-register: true
        group: SEATA-GROUP
    consul:
      host: 127.0.0.1
      port: 8500
      config:
        enabled: false
      discovery:
        enabled: true
        register: true
        instance-id: ${spring.application.name}-${server.port}
        health-check-path: /actuator/health
        health-check-interval: 30s
  profiles:
    active: seata-xa
springdoc:
  swagger-ui.path: /swagger-ui.html

logging:
  level:
    org.springframework: DEBUG
