spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useSSL=false
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: create
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:8500
        registration:
          pkce:
            redirect-uri: "http://127.0.0.1:8000/login/oauth2/code/{registrationId}"
            client-name: pkce
            provider: spring
            authorization-grant-type: authorization_code
            client-id: pkce-client
            client-secret: pkce
            scope: openid,email
server:
  port: 8000
