spring:
  data:
    redis:
      cluster:
        nodes:
        - 10.10.10.50:7001
        - 10.10.10.50:7002
        - 10.10.10.51:7001
        - 10.10.10.51:7002
        - 10.10.10.52:7001
        - 10.10.10.52:7002
      #host: 127.0.0.1 # Redis server host.'
      password:  123456     # Login password of the redis server.
      #port: 6379  # Redis server port.'
      jedis:
        pool:
          max-active: 8
          min-idle: 10
          max-wait: 1
          max-idle: 1
      timeout: 60