server:
  port: 7999
  max-http-request-header-size: 10240
  tomcat:
    max-http-response-header-size: 10240
spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  profiles:
    active: nacos-routes
  application:
    name: gateway-service
logging:
  level:
    org.springframework: debug