spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
         # jwk-set-uri: http://localhost:8500/oauth2/jwks
          issuer-uri: http://localhost:8500

server:
  port: 8301

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
