spring:
  application:
    name: spring-skywalking
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: 127.0.0.1
      #password:
      port: 6379
server:
  port: 9009
