spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML5
    enabled: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
    web-application-type: reactive
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: b7cd30562123ac359386
            client-secret: cf4b14d5ba4dbc0b7d54a0a623e1509c20c5782f
            provider: github
            scope: read:user,public_repo
          messaging-client-oidc:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: messaging-client-oidc
          messaging-client-authorization-code:
              provider: spring
              client-id: messaging-client
              client-secret: secret
              authorization-grant-type: authorization_code
              redirect-uri: "http://127.0.0.1:8080/authorized"
              scope: message.read,message.write
              client-name: messaging-client-authorization-code
          messaging-client-client-credentials:
              provider: spring
              client-id: messaging-client
              client-secret: secret
              authorization-grant-type: client_credentials
              scope: message.read,message.write
              client-name: messaging-client-client-credentials
          messaging-client-device-code:
              provider: spring
              client-id: device-messaging-client
              client-authentication-method: none
              authorization-grant-type: urn:ietf:params:oauth:grant-type:device_code
              scope: message.read,message.write
              client-name: messaging-client-device-code
        provider:
          spring:
            issuer-uri: http://localhost:8500
server:
  port: 8304

resource-uri: https://api.github.com/user/repos

messages:
  base-uri: http://127.0.0.1:8301/messages
