spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

server:
  port: 8201
