spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML5
    enabled: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
server:
  port: 9088

