server:
  servlet:
    session:
      timeout: 10000  # Session timeout. If a duration suffix is not specified, secondsis used.
spring:
  session:
    redis:
      flush-mode: on_save  # Sessions flush mode.
      namespace: spring:session  # Namespace for keys used to store sessions
    store-type: redis    # Session store type.
  data:
    redis:
      host: 127.0.0.1 # Redis server host.'
      password:      # Login password of the redis server.
      port: 6379  # Redis server port.'