server:
  servlet:
    session:
      timeout: 10000  # Session timeout. If a duration suffix is not specified, secondsis used.
spring:
  datasource:
    url: jdbc:h2:mem:testdb;
  data:
    redis:
      host: 127.0.0.1 # Redis server host.'
      password:      # Login password of the redis server.
      port: 6379  # Redis server port.'
  session:
    store-type: jdbc    # Session store type.
  h2:
    console:
      enabled: true
      path: /h2