spring:
  application:
    name: chatgpt-model-service
  datasource:
    url: jdbc:mysql://localhost:3306/chatgpt?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: false
    database: mysql
  profiles:
    active: dev
server:
  port: 7888
