spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
    web-application-type: reactive
  application:
    name: security-auth-service
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML5
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8200/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8200/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
server:
  port: 8200
jwt:
  token:
    expired: 3000000
    refresh:
      expired: 60000000
